### ISSUE TITLE
NuGet Release Notes point to (currently) missing tags

### ISSUE THREAD

**Issue by TheConstructor** [CopyText/TextCopy#200]
Hi,

I just realized there have been new versions released. After finding out that they are not listed as [GitHub releases](https://github.com/CopyText/TextCopy/releases), I headed over to [NuGet](https://www.nuget.org/packages/TextCopy) and saw that [4.0.0](https://www.nuget.org/packages/TextCopy/4.0.0) and [4.1.0](https://www.nuget.org/packages/TextCopy/4.1.0) are linking to GitHub-tags, that can not be found right now.

You probably just missed to push the two tags to GitHub, maybe, as pushing tags may require special git-options.

Best regards & thank you for your work!

TC

**Comment by SimonCropp** [comment]
sorry. fixed
