### ISSUE TITLE
add your GH sponsor link

### ISSUE THREAD

**Issue by SimonCropp** [CopyText/TextCopy#208]
@mfkl can you enable GH sponsors and add your link here https://github.com/CopyText/TextCopy/blob/master/.github/FUNDING.yml

Also can you create a tidelift account and i will add you

**Comment by mfkl** [comment]
Ok, I'll do it soon.

**Comment by mfkl** [comment]
Waiting on Stripe (and then GitHub) to approve my Sponsors account. 

For tidelift the email for my account is me@martinfinkel.com

**Comment by mfkl** [comment]
GitHub sponsors isn't supported in my location, according to GitHub support staff.

**Comment by SimonCropp** [comment]
in that case i will remove mine for now
