### ISSUE TITLE
Can't clear the clipboard, or I don't know how to do it?

### ISSUE THREAD

**Issue by Tam66662** [CopyText/TextCopy#220]
#### Preamble

 * TextCopy 4.2.0
 * .NET Standard 2.0.3
 * Visual Studio 2019

#### Describe the bug

Hi,

I'm using your nuget package, and I've been able to get a Xamarin Android project working with your package to get the clipboard text.  However, I have a timer that attempts to check the clipboard every second, and it keeps getting whatever I have already received.

Is there a way to clear the text from the clipboard after I have processed it?

Thanks,
Tam

#### Minimal Repro

```
        /// <summary>
        /// This method will check the clipboard for any text every timer interval.  If it finds any, it will place it into the clipboard textbox entry automatically.
        /// </summary>
        /// <param name="state"></param>
        private void CheckClipboard(object state)
        {
            Device.BeginInvokeOnMainThread(async () =>
            {
                LogManager.Verbose($"CheckClipboard called");
                var clipboardText = await ClipboardService.GetTextAsync();
                if (!string.IsNullOrEmpty(clipboardText))
                {
                    var m = Regex.Match(clipboardText, @"^http(s|)://(\S+)");
                    if (m.Groups.Count > 2)
                    {
                        this.UrlToAdd = clipboardText;

                        // How do I clear the clipboard??
                    }
                }
            });
        }
```
#### Output

When I run the above code on my Android device, and I open say YouTube and copy a video link, I get a log that says this:
```
2020/06/30 23:10:40.839086|F:file.cs|M:CheckClipboard|L:152|CheckClipboard called
2020/06/30 23:10:41.839935|F:file.cs|M:CheckClipboard|L:152|CheckClipboard called
2020/06/30 23:10:42.841258|F:file.cs|M:CheckClipboard|L:152|CheckClipboard called
2020/06/30 23:10:43.841562|F:file.cs|M:CheckClipboard|L:152|CheckClipboard called
2020/06/30 23:10:43.854555|F:file.cs|M:OnViewModelPropertyChanged|L:169|UrlToAdd = https://youtu.be/o6o0bAncepk
2020/06/30 23:10:44.842875|F:file.cs|M:CheckClipboard|L:152|CheckClipboard called
2020/06/30 23:10:44.863852|F:file.cs|M:OnViewModelPropertyChanged|L:169|UrlToAdd = https://youtu.be/o6o0bAncepk
2020/06/30 23:10:45.841666|F:file.cs|M:CheckClipboard|L:152|CheckClipboard called
2020/06/30 23:10:45.861871|F:file.cs|M:OnViewModelPropertyChanged|L:169|UrlToAdd = https://youtu.be/o6o0bAncepk
```

**Comment by Tam66662** [comment]
OK, I will admit that I am not a genius.  All you have to do to clear the clipboard is to set the text empty:

```
await ClipboardService.SetTextAsync("");
```

I will now crawl back into the hole from whence I came.

**Comment by SimonCropp** [comment]
glad u got it working. should we add an explicit Clear method?

**Comment by Tam66662** [comment]
No, maybe just in your readme.md show an example of how to clear it using SetText? :)  

I searched for the word "clear" in your github before I submitted this issue, and couldn't find anything.

**Comment by mfkl** [comment]
> maybe just in your readme.md show an example of how to clear it using SetText? :)

Would you like to contribute a PR for this?

**Comment by Tam66662** [comment]
Sure, I could give it a shot 👍
