### ISSUE TITLE
Linux needs to use the "-sel clip" option

### ISSUE THREAD

**Issue by AidanMcK** [CopyText/TextCopy#236]
On linux mint, (and after installing xclip), the system clipboard contents are not used.

Adding the "-sel clip" parameter to the xclip function calls fixes this problem (at least on Linux Mint 19.3 Cinnamon).

**Comment by SimonCropp** [comment]
@AidanMcK can you submit a PR

**Comment by AidanMcK** [comment]
I've no time for that, sorry. The two lines that need to be updated are:

`BashRunner.Run($"cat {tempFileName} | xclip -sel clip");`

and:

`BashRunner.Run($"xclip -sel clip -o > {tempFileName}");`

**Comment by mfkl** [comment]
> I've no time for that, sorry. 

Since you already went through the effort of figuring out what needs fixing, which is what takes the most time usually, forking and opening a PR is really the quick part :-) You can see this as a way to contribute back to the community, for the time that TextCopy saved you until now.

**Comment by SimonCropp** [comment]
@AidanMcK looking at the code we already do `cat {tempFileName} | xclip -i -selection clipboard`   https://github.com/CopyText/TextCopy/blob/master/src/TextCopy/LinuxClipboard_2.0.cs#L21

which i believe is the long form of `-sel clip`?

**Comment by AidanMcK** [comment]
Yes you are right - it was fixed up in [issue 15](https://github.com/CopyText/TextCopy/issues/15) a long time ago. Somehow I was using a very old version. I should have checked the code - sorry!
