### ISSUE TITLE
IsAvailable because of xclip

### ISSUE THREAD

**Issue by KoalaBear84** [CopyText/TextCopy#291]
#### Is the feature request related to a problem

Copying on Linux when xclip is not available results in an exception.

#### Describe the solution

Possible to add some `IsAvailable` method/property check to it?

#### Describe alternatives considered

Or is there a proposed alternative?

#### Additional context

I've read #131 but it's different

**Comment by SimonCropp** [comment]
@KoalaBear84 sounds reasonable. do you want to submit a pull request?

**Comment by KoalaBear84** [comment]
@SimonCropp A user reported it https://github.com/KoalaBear84/OpenDirectoryDownloader/issues/38

Sorry, I have no Linux installed myself, and also no knowledge how to check it. Hopefully someone who does sees this and can check it.

For now will resort to error handling so at least it doesn't take the whole app with it.

**Comment by SimonCropp** [comment]
feel free to submit a pr if u ever get around to it
