### ISSUE TITLE
Uno Platform support

### ISSUE THREAD

**Issue by carldebilly** [CopyText/TextCopy#476]
# Please add support for [Uno Platform](https://github.com/unoplatform/uno)

This would add a lot of new platforms to your already impressive list:
* Uno-WASM
* WinUI 3 (successor of UWP)
* Skia (Windows-GTK, Linux-GTK, Tizen)

**Comment by SimonCropp** [comment]
Would love to support those. Do you want to have a go at a Pull Request for any of them?

**Comment by carldebilly** [comment]
Let me check what I can do ;-)
