### ISSUE TITLE
Can't get text from clipboard (ConsoleApplication)

### ISSUE THREAD

**Issue by ItSkary** [CopyText/TextCopy#505]
#### Preamble
To replicate the bug i run the below console application in debug mode, when console stop at frist ReadKey i go to notepad and copy some text. Then return back to console application and press enter (to trigger the ReadKey).
Breakpoint setted over "phrase" variable break execution and i can see that ClipboardService.GetText() return an empty stirng, even if i have put some text into the clipboard few second before. If i go back to notepad and press Ctrl+V the text placed in the clipboard is written (so there was text into the clipboard)

 * Visual Studio 2019 on Windows 10
 * [.NET 4.8]
 * TextCopy 4.3.1

`static void Main(string[] args) {
Console.ReadKey();
      string phrase = ClipboardService.GetText();
      Console.ReadKey();}
`

#### Describe the bug
If i try to use the library from a console application i can't read the clipboard content, every time it appear empty even if not.

**Comment by SimonCropp** [comment]
sorry. i cant reproduce this. can you submit a failing test as a PR
