### ISSUE TITLE
Outdated example in readme

### ISSUE THREAD

**Issue by hhyyrylainen** [CopyText/TextCopy#517]
#### Describe the bug

The example in the main readme on Github https://github.com/CopyText/TextCopy seems to be outdated and I was very confused why the example code didn't work. I actually already had that code in my project, but it stopped compiling while upgrading the nuget packages. Luckily the linked example code https://github.com/CopyText/TextCopy/blob/master/src/BlazorSample/Program.cs#L6-L13 revealed that I actually need `serviceCollection.AddSingleton<IClipboard>(_ => new BlazorClipboard(_.GetRequiredService<IJSRuntime>()));`

I think the example in the main readme file should be updated to reflect the new usage of this library.

#### Minimal Repro

`serviceCollection.InjectClipboard();`
does not compile

#### Submit a PR that fixes the bug

Submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.

**Comment by SimonCropp** [comment]
fixed

**Comment by SimonCropp** [comment]
ok. i reverted that change. serviceCollection.InjectClipboard(); should work for u again

**Comment by hhyyrylainen** [comment]
Can confirm that `serviceCollection.InjectClipboard();` now works again in version 6.1.0. Thanks for the fix.
