### ISSUE TITLE
Net Core 6 Blazor Web Assembly Error

### ISSUE THREAD

**Issue by kirkey** [CopyText/TextCopy#635]
I am able to use this feature on development but does not work when published on IIS.
On my Blazor Page:
`[Inject] private IClipboard? Clipboard { get; set; }`

and a function:
`
private async void CopyMessage(string message)
{
        await Clipboard!.SetTextAsync(message);

        Snackbar.Add("The Template Message was copied to Clipboard", Severity.Success);
}
`

produces an error:
blazor.webassembly.js:1 ThreadPool Callback threw an unhandled exception of type Microsoft.JSInterop.JSException
@ blazor.webassembly.js:1

window.Module.s.printErr 
put_char @ dotnet.6.0.11.qyyrkvd9ti.js:1
write @ dotnet.6.0.11.qyyrkvd9ti.js:1
write @ dotnet.6.0.11.qyyrkvd9ti.js:1
doWritev @ dotnet.6.0.11.qyyrkvd9ti.js:1
_fd_write @ dotnet.6.0.11.qyyrkvd9ti.js:1
$func8741 @ dotnet.wasm:0x1c9f80
$func8952 @ dotnet.wasm:0x1daf61
$func8953 @ dotnet.wasm:0x1db001
$func8954 @ dotnet.wasm:0x1db047
$func3482 @ dotnet.wasm:0xcc250
$func3481 @ dotnet.wasm:0xcc231
$func3217 @ dotnet.wasm:0xc4ea4
$mono_background_exec @ dotnet.wasm:0x9430f
Module._mono_background_exec @ dotnet.6.0.11.qyyrkvd9ti.js:1
pump_message @ dotnet.6.0.11.qyyrkvd9ti.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.6.0.11.qyyrkvd9ti.js:1
$func2392 @ dotnet.wasm:0x942c0
$func3216 @ dotnet.wasm:0xc4de6
$func219 @ dotnet.wasm:0x1a4fa
$func167 @ dotnet.wasm:0xce60
$func166 @ dotnet.wasm:0xbd73
$func2815 @ dotnet.wasm:0xabec4
$func1619 @ dotnet.wasm:0x6fc85
$func1623 @ dotnet.wasm:0x702f2
$mono_wasm_invoke_method @ dotnet.wasm:0x969f
Module._mono_wasm_invoke_method @ dotnet.6.0.11.qyyrkvd9ti.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet:19
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
b @ blazor.webassembly.js:1
invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
invokeWhenHeapUnlocked @ blazor.webassembly.js:1
A @ blazor.webassembly.js:1
N @ blazor.webassembly.js:1
dispatchGlobalEventToAllElements @ blazor.webassembly.js:1
onGlobalEvent @ blazor.webassembly.js:1

**Comment by SimonCropp** [comment]
@kirkey happy to accept a PullRequest that fixes this
